name: PHPOnl pull request events

on:
  pull_request:
    branches:
      - master
    type:
      - opened
env:
  PRIMARY_DOMAIN: php.onl
  REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-domain:
    if: |
      github.event.action == 'opened'
        && contains(toJson(github.event.pull_request.labels), 'register domain')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: ./.github/actions/check-domain
        with:
          domainDataUrl: ${{ secrets.DOMAIN_DATA_URL }}
  create-domain:
    if: |
      github.event.action == 'closed' && github.event.pull_request.merged == true
        && contains(toJson(github.event.pull_request.labels), 'register domain')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: ./.github/actions/create-domain
        with:
          apiUrl: ${{ secrets.DNS_API_URL }}
          apiToken: ${{ secrets.DNS_API_TOKEN }}
          loggerUrl: ${{ secrets.LOGGER_URL }}
